/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查 API 进程是否存活 */
        get: operations["get_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查 API 是否可以接收请求 */
        get: operations["get_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Trip Endpoint
         * @description 创建新旅行的API端点
         */
        post: operations["created_trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip Response */
        get: operations["get_trip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/planning-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Planning Endpoint */
        post: operations["start_planning_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/planning-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Planning Events */
        get: operations["list_planning_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plan Versions */
        get: operations["list_plan_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/plans/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan Endpoint */
        get: operations["get_plan_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Feedback Endpoint
         * @description 保存结构化反馈，并按需启动下一版规划。
         *
         *     如果反馈缺少明确操作，则返回 200 并要求用户澄清；
         *     否则正常返回 202 和可选的重新规划任务。
         */
        post: operations["create_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/manual-edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manual Plan Edit */
        post: operations["create_manual_plan_edit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Activity
         * @description 行程中单个活动
         */
        Activity: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["ActivityKind"];
            /** Title */
            title: string;
            /** Place Id */
            place_id?: string | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Route Leg Id */
            route_leg_id?: string | null;
            estimated_cost: components["schemas"]["Money"];
            /**
             * Priority
             * @default 50
             */
            priority: number;
            /** Locked */
            locked: boolean;
            indoor_outdoor: components["schemas"]["IndoorOutdoor"];
            /** Reason */
            reason: string;
            /** Notes */
            notes?: string[];
            /** @default planner */
            source_type: components["schemas"]["ActivitySourceType"];
        };
        /**
         * ActivityKind
         * @description 行程单活动类型枚举
         * @enum {string}
         */
        ActivityKind: "visit" | "meal" | "rest" | "transfer" | "free_time" | "check_in" | "check_out";
        /**
         * ActivitySourceType
         * @description 活动数据来源类型
         * @enum {string}
         */
        ActivitySourceType: "planner" | "user" | "replacement" | "fixed_rule";
        /** AddExcludedPlaceOperation */
        AddExcludedPlaceOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_excluded_place";
            /** Place Name */
            place_name: string;
            /** Reason */
            reason?: string | null;
        };
        /** AddRequiredPlaceOperation */
        AddRequiredPlaceOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_required_place";
            /** Place Name */
            place_name: string;
            /** Reason */
            reason?: string | null;
        };
        /**
         * BudgetCategory
         * @description 预算分类枚举
         * @enum {string}
         */
        BudgetCategory: "intercity_transport" | "accommodation" | "food" | "admission" | "local_transport" | "shopping" | "contingency" | "other";
        /**
         * BudgetItem
         * @description 单条预算明细
         */
        BudgetItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            category: components["schemas"]["BudgetCategory"];
            /** Label */
            label: string;
            /** Date */
            date: string | null;
            /** Activity Id */
            activity_id?: string | null;
            amount: components["schemas"]["Money"];
            /** Estimated */
            estimated: boolean;
            source?: components["schemas"]["SourceRef"] | null;
        };
        /**
         * BudgetSummary
         * @description 预算汇总
         */
        BudgetSummary: {
            limit: components["schemas"]["Money"];
            /** Items */
            items?: components["schemas"]["BudgetItem"][];
            /** Totals By Category */
            totals_by_category?: {
                [key: string]: components["schemas"]["Money"];
            };
            planned_total: components["schemas"]["Money"];
            /** Remaining Amount */
            remaining_amount: number;
            /** Currency */
            currency: string;
            /** Within Budget */
            within_budget: boolean;
            /** Exchange Rates */
            exchange_rates?: {
                [key: string]: components["schemas"]["ExchangeRate"];
            };
        };
        /**
         * ConstraintCode
         * @description 约束校验违规编码枚举，每一个编码对应一条校验规则
         * @enum {string}
         */
        ConstraintCode: "DATE_OUT_OF_RANGE" | "ACTIVITY_OVERLAP" | "PLACE_CLOSED" | "TRANSFER_TIME_INSUFFICIENT" | "DAILY_END_TIME_EXCEEDED" | "MAX_WALKING_EXCEEDED" | "BUDGET_EXCEEDED" | "WEATHER_MISMATCH" | "REQUIRED_PLACE_MISSING" | "EXCLUDED_PLACE_PRESENT" | "TOO_MANY_ACTIVITIES" | "DATA_INCOMPLETE";
        /**
         * ConstraintReport
         * @description 约束校验报告
         *     行程约束校验完整输出，汇总全部违规项，记录校验元信息，自带业务一致性校验
         */
        ConstraintReport: {
            /** Passed */
            passed: boolean;
            /** Violations */
            violations?: components["schemas"]["ConstraintViolation"][];
            /** Checked Rule Codes */
            checked_rule_codes?: string[];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Engine Version */
            engine_version: string;
        };
        /**
         * ConstraintSeverity
         * @description 约束校验违规严重等级枚举
         * @enum {string}
         */
        ConstraintSeverity: "error" | "warning" | "info";
        /**
         * ConstraintViolation
         * @description 单条约束违规记录：
         *     保存某一条规则触发后的全部上下文信息，用于前端展示、自动修复、日志排查
         */
        ConstraintViolation: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            code: components["schemas"]["ConstraintCode"];
            severity: components["schemas"]["ConstraintSeverity"];
            /** Day */
            day?: string | null;
            /** Activity Id */
            activity_id?: string | null;
            /** Message */
            message: string;
            /** Actual */
            actual?: {
                [key: string]: unknown;
            } | null;
            /** Expected */
            expected?: {
                [key: string]: unknown;
            } | null;
            /** Repair Hint */
            repair_hint?: string | null;
            /** Rule Version */
            rule_version: string;
        };
        /** CurrentPlanResponse */
        CurrentPlanResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Version */
            version: number;
            /** Parent Version */
            parent_version: number | null;
            status: components["schemas"]["PlanStatus"];
            itinerary: components["schemas"]["Itinerary"];
            constraint_report: components["schemas"]["ConstraintReport"];
            /** Change Summary */
            change_summary: string;
            trigger: components["schemas"]["PlanTrigger"];
            /**
             * Planning Run Id
             * Format: uuid
             */
            planning_run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Accepted At */
            accepted_at: string | null;
        };
        /**
         * DataQuality
         * @description 数据质量枚举，标记外部来源数据可信度
         * @enum {string}
         */
        DataQuality: "verified" | "estimated" | "incomplete" | "stale" | "mock";
        /**
         * DateRange
         * @description 日期区间
         *     用于旅行的行程起止时间
         */
        DateRange: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /**
         * DayPlan
         * @description 单日行程：某一天全部活动、路段、天气、统计、警告
         */
        DayPlan: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Day Number */
            day_number: number;
            /**
             * Theme
             * @default 待规划
             */
            theme: string;
            weather?: components["schemas"]["WeatherDay"] | null;
            /** Activities */
            activities?: components["schemas"]["Activity"][];
            /** Route Legs */
            route_legs?: components["schemas"]["RouteLeg"][];
            statistics: components["schemas"]["DayStatistics"];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * DayStatistics
         * @description 单日行程统计指标
         */
        DayStatistics: {
            /**
             * Activity Count
             * @default 0
             */
            activity_count: number;
            /**
             * Walking Meters
             * @default 0
             */
            walking_meters: number;
            /**
             * Transfer Minutes
             * @default 0
             */
            transfer_minutes: number;
            /**
             * Planned Minutes
             * @default 0
             */
            planned_minutes: number;
            estimated_cost: components["schemas"]["Money"];
        };
        /**
         * DietaryPreference
         * @description 饮食偏好枚举，用于筛选餐厅、餐饮推荐
         * @enum {string}
         */
        DietaryPreference: "vegetarian" | "vegan" | "halal" | "gluten_free" | "no_pork" | "no_beef" | "seafood_free" | "nut_free";
        /**
         * ExchangeRate
         * @description 汇率领域模型，用于多币种预算换算
         */
        ExchangeRate: {
            /** From Currency */
            from_currency: string;
            /** To Currency */
            to_currency: string;
            /** Rate */
            rate: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            source?: components["schemas"]["SourceRef"] | null;
        };
        /** FeedbackCreateRequest */
        FeedbackCreateRequest: {
            /** Base Plan Version */
            base_plan_version: number;
            /** Message */
            message: string;
            /** Client Operations */
            client_operations?: (components["schemas"]["SetBudgetOperation"] | components["schemas"]["SetMaxWalkingOperation"] | components["schemas"]["AddRequiredPlaceOperation"] | components["schemas"]["AddExcludedPlaceOperation"])[];
            /**
             * Auto Start Replanning
             * @default true
             */
            auto_start_replanning: boolean;
        };
        /** FeedbackRecordResponse */
        FeedbackRecordResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Base Plan Version */
            base_plan_version: number;
            /** Message */
            message: string;
            /** Operations */
            operations: (components["schemas"]["SetBudgetOperation"] | components["schemas"]["SetMaxWalkingOperation"] | components["schemas"]["AddRequiredPlaceOperation"] | components["schemas"]["AddExcludedPlaceOperation"])[];
            scope: components["schemas"]["FeedbackScope"];
            /** Requires Clarification */
            requires_clarification: boolean;
            /** Clarification Question */
            clarification_question: string | null;
            /** Planning Run Id */
            planning_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            feedback: components["schemas"]["FeedbackRecordResponse"];
            planning_run: components["schemas"]["PlanningRunResponse"] | null;
            /** Events Url */
            events_url: string | null;
        };
        /** FeedbackScope */
        FeedbackScope: {
            /** Dates */
            dates?: string[];
            /** Activity Ids */
            activity_ids?: string[];
            /**
             * Global
             * @default true
             */
            global: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndoorOutdoor
         * @description 场所属性
         * @enum {string}
         */
        IndoorOutdoor: "indoor" | "outdoor" | "mixed" | "unknown";
        /**
         * Itinerary
         * @description 完整行程
         */
        Itinerary: {
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Title */
            title: string;
            /** Destination */
            destination: string;
            /** Timezone */
            timezone: string;
            date_range: components["schemas"]["DateRange"];
            /** Days */
            days?: components["schemas"]["DayPlan"][];
            budget: components["schemas"]["BudgetSummary"];
            /** General Notes */
            general_notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** ManualActivityEdit */
        ManualActivityEdit: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Start Time */
            start_time: string;
            /** End Time */
            end_time: string;
            /**
             * Removed
             * @default false
             */
            removed: boolean;
            /**
             * Is New
             * @default false
             */
            is_new: boolean;
        };
        /** ManualDayEdit */
        ManualDayEdit: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Activities */
            activities: components["schemas"]["ManualActivityEdit"][];
        };
        /** ManualPlanEditRequest */
        ManualPlanEditRequest: {
            /** Base Plan Version */
            base_plan_version: number;
            /** Days */
            days: components["schemas"]["ManualDayEdit"][];
        };
        /** ManualPlanEditResponse */
        ManualPlanEditResponse: {
            plan: components["schemas"]["CurrentPlanResponse"];
            planning_run: components["schemas"]["PlanningRunResponse"];
        };
        /**
         * Money
         * @description 金额领域模型
         *     业务约定：amount 使用最小货币单位整数，例如人民币以「分」为单位，
         *     100 代表 1 元；避免浮点数精度丢失。
         */
        Money: {
            /**
             * Amount
             * @description 最小货币单位整数
             */
            amount: number;
            /** Currency */
            currency: string;
        };
        /**
         * OutdoorSuitability
         * @description 户外活动适宜度枚举
         * @enum {string}
         */
        OutdoorSuitability: "good" | "acceptable" | "poor" | "unknown";
        /**
         * Pace
         * @description 行程节奏枚举，控制每日行程松紧程度
         * @enum {string}
         */
        Pace: "relaxed" | "balanced" | "packed";
        /** PlanListResponse */
        PlanListResponse: {
            /** Items */
            items: components["schemas"]["PlanVersionSummary"][];
        };
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "draft" | "valid" | "accepted" | "superseded";
        /**
         * PlanTrigger
         * @enum {string}
         */
        PlanTrigger: "initial" | "user_feedback" | "data_change" | "manual_validation";
        /** PlanVersionSummary */
        PlanVersionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Version */
            version: number;
            /** Parent Version */
            parent_version: number | null;
            status: components["schemas"]["PlanStatus"];
            /** Day Count */
            day_count: number;
            planned_total: components["schemas"]["Money"];
            /** Error Count */
            error_count: number;
            /** Warning Count */
            warning_count: number;
            /** Change Summary */
            change_summary: string;
            trigger: components["schemas"]["PlanTrigger"];
            /**
             * Planning Run Id
             * Format: uuid
             */
            planning_run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlanningEventListResponse */
        PlanningEventListResponse: {
            /** Items */
            items: components["schemas"]["PlanningEventResponse"][];
        };
        /** PlanningEventResponse */
        PlanningEventResponse: {
            /** Id */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            type: components["schemas"]["PlanningEventType"];
            /** Step */
            step: string | null;
            /** Message */
            message: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PlanningEventType
         * @enum {string}
         */
        PlanningEventType: "run_started" | "step_started" | "step_completed" | "constraint_found" | "repair_started" | "plan_created" | "review_required" | "run_completed" | "run_failed";
        /** PlanningRunResponse */
        PlanningRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            trigger: components["schemas"]["PlanningRunTrigger"];
            status: components["schemas"]["PlanningRunStatus"];
            /** Progress Percent */
            progress_percent: number;
            /** Current Step */
            current_step: string | null;
            /** Base Plan Version */
            base_plan_version: number | null;
            /** Result Plan Version */
            result_plan_version: number | null;
            /** Feedback Id */
            feedback_id: string | null;
            /** Repair Attempts */
            repair_attempts: number;
            /** Max Repair Attempts */
            max_repair_attempts: number;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * PlanningRunStatus
         * @enum {string}
         */
        PlanningRunStatus: "queued" | "researching" | "planning" | "validating" | "repairing" | "waiting_for_review" | "completed" | "failed" | "cancelled";
        /**
         * PlanningRunTrigger
         * @enum {string}
         */
        PlanningRunTrigger: "initial" | "feedback" | "data_change";
        /**
         * RouteLeg
         * @description 单段行程路段：A点到B点的通行信息
         */
        RouteLeg: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Origin Place Id */
            origin_place_id: string;
            /** Destination Place Id */
            destination_place_id: string;
            mode: components["schemas"]["TransportMode"];
            /** Departure Time */
            departure_time?: string | null;
            /** Arrival Time */
            arrival_time?: string | null;
            /** Duration Minutes */
            duration_minutes: number;
            /** Distance Meters */
            distance_meters: number;
            /** Walking Meters */
            walking_meters: number;
            cost?: components["schemas"]["Money"] | null;
            /** Polyline */
            polyline?: string | null;
            /** Instructions Summary */
            instructions_summary?: string | null;
            source: components["schemas"]["SourceRef"];
        };
        /** SetBudgetOperation */
        SetBudgetOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_budget";
            total_budget: components["schemas"]["Money"];
            /** Hard Limit */
            hard_limit: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** SetMaxWalkingOperation */
        SetMaxWalkingOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_max_walking";
            /** Meters Per Day */
            meters_per_day: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * SourceRef
         * @description 外部数据源引用记录
         *     记录这条业务数据来自哪个第三方API，抓取时间、过期时间、数据质量。
         */
        SourceRef: {
            /** Provider */
            provider: string;
            /** Source Id */
            source_id?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Expires At */
            expires_at?: string | null;
            data_quality: components["schemas"]["DataQuality"];
        };
        /** StartPlanningResponse */
        StartPlanningResponse: {
            planning_run: components["schemas"]["PlanningRunResponse"];
            /** Events Url */
            events_url: string;
        };
        /**
         * TransportMode
         * @description 可选用的出行交通方式
         * @enum {string}
         */
        TransportMode: "walking" | "public_transit" | "taxi" | "driving" | "cycling" | "mixed";
        /**
         * TripConstraints
         * @description 行程硬性约束条件：算法必须遵守，不满足就不能生成方案
         */
        TripConstraints: {
            total_budget: components["schemas"]["Money"];
            /**
             * Budget Is Hard Limit
             * @default true
             */
            budget_is_hard_limit: boolean;
            /**
             * Daily Start Time
             * @default 09:00
             */
            daily_start_time: string;
            /**
             * Daily End Time
             * @default 21:00
             */
            daily_end_time: string;
            /**
             * Max Walking Meters Per Day
             * @default 12000
             */
            max_walking_meters_per_day: number | null;
            /**
             * Max Activities Per Day
             * @default 5
             */
            max_activities_per_day: number;
            /**
             * Minimum Transfer Buffer Minutes
             * @default 10
             */
            minimum_transfer_buffer_minutes: number;
            /**
             * Rest Minutes Per Day
             * @default 60
             */
            rest_minutes_per_day: number;
            /** Required Place Names */
            required_place_names?: string[];
            /** Excluded Place Names */
            excluded_place_names?: string[];
            /**
             * Accessible Only
             * @default false
             */
            accessible_only: boolean;
        };
        /**
         * TripCreateRequest
         * @description 创建旅行请求。
         *
         *     它和领域 TripRequest 当前字段相同，但拥有独立的 OpenAPI Schema 名称。
         *     客户端无法提交 id、status、revision 或 current_plan_version。
         */
        TripCreateRequest: {
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Destination Timezone */
            destination_timezone: string;
            date_range: components["schemas"]["DateRange"];
            /** Travelers */
            travelers: number;
            preferences: components["schemas"]["TripPreferences"];
            constraints: components["schemas"]["TripConstraints"];
            /**
             * Locale
             * @default zh-CN
             */
            locale: string;
            /**
             * Display Currency
             * @default CNY
             */
            display_currency: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * TripPreferences
         * @description 用户行程偏好：主观喜好，不做硬性强制约束，供算法做加权推荐
         */
        TripPreferences: {
            /** Interests */
            interests?: components["schemas"]["WeightedPreference"][];
            /** Avoid */
            avoid?: string[];
            /** Dietary */
            dietary?: components["schemas"]["DietaryPreference"][];
            /** Transport Modes */
            transport_modes?: components["schemas"]["TransportMode"][];
            /** Accommodation Notes */
            accommodation_notes?: string | null;
            /** @default balanced */
            pace: components["schemas"]["Pace"];
            /** Must Visit Place Names */
            must_visit_place_names?: string[];
        };
        /** TripResponse */
        TripResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["TripStatus"];
            /** Revision */
            revision: number;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Destination Timezone */
            destination_timezone: string;
            date_range: components["schemas"]["DateRange"];
            /** Travelers */
            travelers: number;
            preferences: components["schemas"]["TripPreferences"];
            constraints: components["schemas"]["TripConstraints"];
            /** Locale */
            locale: string;
            /** Display Currency */
            display_currency: string;
            /** Notes */
            notes: string | null;
            /** Current Plan Version */
            current_plan_version: number | null;
            /** Active Planning Run Id */
            active_planning_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TripStatus
         * @enum {string}
         */
        TripStatus: "draft" | "planning" | "needs_review" | "replanning" | "completed" | "failed" | "archived";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeatherCondition
         * @description 天气状况枚举，描述单日天气
         * @enum {string}
         */
        WeatherCondition: "clear" | "partly_cloudy" | "cloudy" | "rain" | "storm" | "snow" | "fog" | "unknown";
        /**
         * WeatherDay
         * @description 某一天目的地的天气预报数据
         */
        WeatherDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            condition: components["schemas"]["WeatherCondition"];
            /** Temperature Min C */
            temperature_min_c?: number | null;
            /** Temperature Max C */
            temperature_max_c?: number | null;
            /** Rain Probability */
            rain_probability?: number | null;
            /** Precipitation Mm */
            precipitation_mm?: number | null;
            /** Sunrise Time */
            sunrise_time?: string | null;
            /** Sunset Time */
            sunset_time?: string | null;
            outdoor_suitability: components["schemas"]["OutdoorSuitability"];
            source: components["schemas"]["SourceRef"];
        };
        /**
         * WeightedPreference
         * @description 带权重的偏好项
         *     value：偏好标签
         *     weight：偏好强度 0<weight≤1，越大代表用户越喜欢
         */
        WeightedPreference: {
            /** Value */
            value: string;
            /** Weight */
            weight: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    created_trip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_planning_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartPlanningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_planning_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_plan_edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPlanEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualPlanEditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
